name: Read File and Send to API
 
on:
  schedule:
    - cron: '*/5 * * * *'
 
jobs:
  send-to-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Read Last Line of File
        id: read_last_line
        run: |
          last_line=$(tail -n 1 remind)
          echo "::set-output name=line::$last_line"

      - name: Send to API
        run: curl -G -d "token=xuiidfcpgi&group=true&content=${{ steps.read_last_line.outputs.line }}" https://nodered.glwsq.cn/weixin2
