name: remind

on:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库内容
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置时区为东八区
      - name: Set timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai

      # 解析 CSV 文件
      - name: Parse CSV and Send reminders
        run: |
          # 安装必要的工具
          sudo apt-get install -y jq

          # 读取 CSV 文件内容
          while IFS=, read -r title content reminder_time; do
            # 跳过标题行
            if [[ "$title" == "标题" ]]; then
              continue
            fi
            
            # 获取当前时间的时间戳（假设系统时区已设置为东八区）
            current_time=$(date +"%Y-%m-%d %H:%M:%S")
            current_timestamp=$(date -d "$current_time" +%s)

            # 将提醒时间转换为时间戳
            reminder_timestamp=$(date -d "$reminder_time" +%s)

            # 打印调试信息
            echo "Reminder time (Local): $reminder_time"
            echo "Current time (Local): $current_time"
            echo "Reminder time (Timestamp): $reminder_timestamp"
            echo "Current time (Timestamp): $current_timestamp"

            # 检查提醒时间是否到了
            if [[ "$reminder_timestamp" -le "$current_timestamp" ]]; then
              # 发送提醒消息的接口调用
              echo "Sending message: title = $title, content = $content"
              curl -X GET "https://nodered.glwsq.cn/weixin2?token=xuiidfcpgi&group=true&content=${title}\n${content}" -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8"
            fi
          done < "remind.csv"  # CSV 文件路径
